#pragma once

#define MONT_SERVER_IP								NULL
#define MONT_SERVER_PORT							12121

#define MONT_TLS_MEM_POOL_DEFAULT_UNIT_CNT			10
#define MONT_TLS_MEM_POOL_DEFAULT_UNIT_CAPACITY		10

#define MONT_SERIAL_BUFFER_SIZE						300
#define MONT_SERV_SESSION_RECV_BUFF_SIZE			1000

#define dfMAX_NUM_OF_MONT_CLIENT_TOOL				5

#define MONT_SERVER_MONITORING_MODE