#pragma once

#define MONT_TLS_MEM_POOL_DEFAULT_UNIT_CNT			100
#define MONT_TLS_MEM_POOL_DEFAULT_UNIT_CAPACITY		100
#define MONT_SERV_SESSION_SEND_BUFF_SIZE			1000
#define MONT_SERV_SESSION_RECV_BUFF_SIZE			1000

//#define MONITOR_DATA_TYPE_MONITOR_CPU_TOTAL				"MONITOR_DATA_TYPE_MONITOR_CPU_TOTAL"
//#define MONITOR_DATA_TYPE_MONITOR_NONPAGED_MEMORY		"MONITOR_DATA_TYPE_MONITOR_NONPAGED_MEMORY"
//#define MONITOR_DATA_TYPE_MONITOR_NETWORK_RECV			"MONITOR_DATA_TYPE_MONITOR_NETWORK_RECV"
//#define MONITOR_DATA_TYPE_MONITOR_NETWORK_SEND			"MONITOR_DATA_TYPE_MONITOR_NETWORK_SEND"
//#define MONITOR_DATA_TYPE_MONITOR_AVAILABLE_MEMORY		"MONITOR_DATA_TYPE_MONITOR_AVAILABLE_MEMORY"